id: IBF4F3BBF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:32:38+00:00'
last_modified: '2022-06-08T13:12:39.517418+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8479
  title: སྡོམ་གསུམ་འགྲེལ་བ་དཔག་བསམ་སྙེ་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1888':
      image_group_id: I1KG8519
      title: ''
      total_pages: 416
      order: 1
      base_file: 1888.txt
    F0FD:
      image_group_id: I1KG8520
      title: ''
      total_pages: 250
      order: 2
      base_file: F0FD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
